version: '3.1'

services:

  php:
    container_name: fbphpsdk-php
    build:
      context: docker/php
    ports:
      - 9000:9000
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker-php-zzz-overrides.ini
